### ISSUE TITLE
这份Demo中的NodePlayer设置实际是没有生效的么?

### ISSUE THREAD

**Issue by NessCurie** [NodeMedia/QLive-Android#1]
查看代码时,发现在nodemediaclient的NodePlayer,java中大部分的成员变量都没有被实际使用,通过方法设置的参数只是赋值给了成员变量,这份demo只是一个可以播放的案例,实际的参数都已经在so库中设定死了对吧?

**Comment by illuspas** [comment]
在jni层也是可以读取java对象的成员变量的，回去学习

**Comment by NessCurie** [comment]
好吧...刚刚试了把onEvent方法注释掉就报错了,jni接触的不多,不过这种写法还没见过...最开始是怀疑jni直接访问java的成员变量和方法,问了做系统和jni的同事说要传参...他应该也没接触过这种办法... 多谢解答了...

**Comment by illuspas** [comment]
不加static修饰的native方法，jni层收到的第二个参数就是调用对象，否则是类
